name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v2
  #       with:
  #         distribution: "zulu"
  #         java-version: "11"
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable" # or: 'beta' or 'master'
  #     - run: flutter pub get
  #     # - run: flutter test
  #     - run: flutter build apk
  #     # - run: flutter build appbundle
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: release-apk
  #         path: build/app/outputs/apk/release/app-release.apk
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta' or 'master'
          architecture: x64
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa
